//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeleeMeDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Connections
    {
        public m_Connections()
        {
            this.m_UserConnections = new HashSet<m_UserConnections>();
        }
    
        public int ConnectionId { get; set; }
        public string ConnectionName { get; set; }
        public string ConnectionIcon { get; set; }
    
        public virtual ICollection<m_UserConnections> m_UserConnections { get; set; }
    }
}
