//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeleeMeDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_MeleeStats
    {
        public int meleeStatisticsId { get; set; }
        public int meleeId { get; set; }
        public string meleeWinner { get; set; }
        public string meleeLoser { get; set; }
    
        public virtual m_Melee m_Melee { get; set; }
    }
}
