//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeleeMeDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Melee
    {
        public m_Melee()
        {
            this.m_MeleeStats = new HashSet<m_MeleeStats>();
        }
    
        public int meleeId { get; set; }
        public string challenger { get; set; }
        public string opponent { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual ICollection<m_MeleeStats> m_MeleeStats { get; set; }
    }
}
