//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeleeMeDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_User
    {
        public m_User()
        {
            this.m_Credentials = new HashSet<m_Credentials>();
            this.m_UserConnections = new HashSet<m_UserConnections>();
        }
    
        public int UserId { get; set; }
        public string TwitterUserId { get; set; }
        public string ProfileImageUrl { get; set; }
        public string ScreenName { get; set; }
    
        public virtual ICollection<m_Credentials> m_Credentials { get; set; }
        public virtual ICollection<m_UserConnections> m_UserConnections { get; set; }
    }
}
